`timescale 1ns/1ns

module janko ();
// generated by  HDL Direct 15.20-s005 24-Aug-2005
// on Mon Jan 10 10:41:48 2011
// from janko_lib/JANKO/sch_1

  // global signal glbl.ground;
  // global signal glbl.vcc_circle;

  wire  clk;
  wire  load;
  wire  sw1;
  wire  sw10;
  wire  sw100;
  wire  sw101;
  wire  sw102;
  wire  sw103;
  wire  sw104;
  wire  sw105;
  wire  sw106;
  wire  sw107;
  wire  sw108;
  wire  sw109;
  wire  sw11;
  wire  sw110;
  wire  sw111;
  wire  sw112;
  wire  sw113;
  wire  sw114;
  wire  sw115;
  wire  sw116;
  wire  sw117;
  wire  sw118;
  wire  sw119;
  wire  sw12;
  wire  sw120;
  wire  sw13;
  wire  sw14;
  wire  sw15;
  wire  sw16;
  wire  sw17;
  wire  sw18;
  wire  sw19;
  wire  sw2;
  wire  sw20;
  wire  sw21;
  wire  sw22;
  wire  sw23;
  wire  sw24;
  wire  sw3;
  wire  sw33;
  wire  sw34;
  wire  sw35;
  wire  sw36;
  wire  sw37;
  wire  sw38;
  wire  sw39;
  wire  sw4;
  wire  sw40;
  wire  sw41;
  wire  sw42;
  wire  sw43;
  wire  sw44;
  wire  sw45;
  wire  sw46;
  wire  sw47;
  wire  sw48;
  wire  sw5;
  wire  sw6;
  wire  sw65;
  wire  sw66;
  wire  sw67;
  wire  sw68;
  wire  sw69;
  wire  sw7;
  wire  sw70;
  wire  sw71;
  wire  sw72;
  wire  sw73;
  wire  sw74;
  wire  sw75;
  wire  sw76;
  wire  sw77;
  wire  sw78;
  wire  sw79;
  wire  sw8;
  wire  sw80;
  wire  sw81;
  wire  sw82;
  wire  sw83;
  wire  sw84;
  wire  sw85;
  wire  sw86;
  wire  sw87;
  wire  sw88;
  wire  sw89;
  wire  sw9;
  wire  sw90;
  wire  sw91;
  wire  sw92;
  wire  sw93;
  wire  sw94;
  wire  sw95;
  wire  sw96;
  wire  sw97;
  wire  sw98;
  wire  sw99;
  wire  unnamed_1_j5st_i2_3;
  wire  unnamed_1_rsmt_i183_1;
  wire  unnamed_1_rsmt_i184_1;
  wire  unnamed_1_rsmt_i185_1;
  wire  unnamed_1_rsmt_i186_1;
  wire  unnamed_1_rsmt_i187_1;
  wire  unnamed_1_rsmt_i188_1;
  wire  unnamed_1_rsmt_i191_1;
  wire  unnamed_1_rsmt_i193_1;
  wire  unnamed_1_rsmt_i194_1;
  wire  unnamed_1_rsmt_i195_1;
  wire  unnamed_1_rsmt_i196_1;

  wire  ground;
  wire  page1_ground;
  wire  vcc_circle;
  wire  page1_vcc_circle;

  assign ground = glbl.ground;
  assign page1_ground = ground;
  assign vcc_circle = glbl.vcc_circle;
  assign page1_vcc_circle = vcc_circle;

  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;

// begin instances 

  j_5_st page1_i2  (.\1 (glbl.ground),
	.\2 (glbl.vcc_circle),
	.\3 (unnamed_1_j5st_i2_3),
	.\4 (clk),
	.\5 (load));

  r_smt page1_i5  (.\1 (sw4),
	.\2 (glbl.vcc_circle));

  r_smt page1_i7  (.\1 (sw3),
	.\2 (glbl.vcc_circle));

  r_smt page1_i8  (.\1 (sw2),
	.\2 (glbl.vcc_circle));

  r_smt page1_i9  (.\1 (sw1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i10  (.\1 (sw5),
	.\2 (glbl.vcc_circle));

  r_smt page1_i11  (.\1 (sw6),
	.\2 (glbl.vcc_circle));

  r_smt page1_i12  (.\1 (sw7),
	.\2 (glbl.vcc_circle));

  r_smt page1_i13  (.\1 (sw8),
	.\2 (glbl.vcc_circle));

  c_smt page1_i14  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i27  (.\1 (sw9),
	.\2 (glbl.vcc_circle));

  c_smt page1_i28  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i29  (.\1 (sw10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i30  (.\1 (sw11),
	.\2 (glbl.vcc_circle));

  r_smt page1_i31  (.\1 (sw12),
	.\2 (glbl.vcc_circle));

  r_smt page1_i32  (.\1 (sw13),
	.\2 (glbl.vcc_circle));

  r_smt page1_i33  (.\1 (sw14),
	.\2 (glbl.vcc_circle));

  r_smt page1_i35  (.\1 (sw15),
	.\2 (glbl.vcc_circle));

  r_smt page1_i36  (.\1 (sw16),
	.\2 (glbl.vcc_circle));

  r_smt page1_i51  (.\1 (sw17),
	.\2 (glbl.vcc_circle));

  c_smt page1_i52  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i53  (.\1 (sw18),
	.\2 (glbl.vcc_circle));

  r_smt page1_i54  (.\1 (sw19),
	.\2 (glbl.vcc_circle));

  r_smt page1_i55  (.\1 (sw20),
	.\2 (glbl.vcc_circle));

  r_smt page1_i56  (.\1 (sw21),
	.\2 (glbl.vcc_circle));

  r_smt page1_i57  (.\1 (sw22),
	.\2 (glbl.vcc_circle));

  r_smt page1_i59  (.\1 (sw23),
	.\2 (glbl.vcc_circle));

  r_smt page1_i60  (.\1 (sw24),
	.\2 (glbl.vcc_circle));

  r_smt page1_i75  (.\1 (sw33),
	.\2 (glbl.vcc_circle));

  c_smt page1_i76  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i77  (.\1 (sw34),
	.\2 (glbl.vcc_circle));

  r_smt page1_i78  (.\1 (sw35),
	.\2 (glbl.vcc_circle));

  r_smt page1_i79  (.\1 (sw36),
	.\2 (glbl.vcc_circle));

  r_smt page1_i80  (.\1 (sw37),
	.\2 (glbl.vcc_circle));

  r_smt page1_i81  (.\1 (sw38),
	.\2 (glbl.vcc_circle));

  r_smt page1_i83  (.\1 (sw39),
	.\2 (glbl.vcc_circle));

  r_smt page1_i84  (.\1 (sw40),
	.\2 (glbl.vcc_circle));

  r_smt page1_i87  (.\1 (sw41),
	.\2 (glbl.vcc_circle));

  c_smt page1_i88  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i89  (.\1 (sw42),
	.\2 (glbl.vcc_circle));

  r_smt page1_i90  (.\1 (sw43),
	.\2 (glbl.vcc_circle));

  r_smt page1_i91  (.\1 (sw44),
	.\2 (glbl.vcc_circle));

  r_smt page1_i92  (.\1 (sw45),
	.\2 (glbl.vcc_circle));

  r_smt page1_i93  (.\1 (sw46),
	.\2 (glbl.vcc_circle));

  r_smt page1_i95  (.\1 (sw47),
	.\2 (glbl.vcc_circle));

  r_smt page1_i96  (.\1 (sw48),
	.\2 (glbl.vcc_circle));

  r_smt page1_i99  (.\1 (sw65),
	.\2 (glbl.vcc_circle));

  r_smt page1_i100  (.\1 (sw66),
	.\2 (glbl.vcc_circle));

  r_smt page1_i101  (.\1 (sw67),
	.\2 (glbl.vcc_circle));

  r_smt page1_i102  (.\1 (sw68),
	.\2 (glbl.vcc_circle));

  c_smt page1_i103  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i104  (.\1 (sw69),
	.\2 (glbl.vcc_circle));

  r_smt page1_i105  (.\1 (sw70),
	.\2 (glbl.vcc_circle));

  r_smt page1_i107  (.\1 (sw71),
	.\2 (glbl.vcc_circle));

  r_smt page1_i108  (.\1 (sw72),
	.\2 (glbl.vcc_circle));

  r_smt page1_i111  (.\1 (sw81),
	.\2 (glbl.vcc_circle));

  r_smt page1_i112  (.\1 (sw82),
	.\2 (glbl.vcc_circle));

  r_smt page1_i113  (.\1 (sw83),
	.\2 (glbl.vcc_circle));

  r_smt page1_i114  (.\1 (sw84),
	.\2 (glbl.vcc_circle));

  c_smt page1_i115  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i116  (.\1 (sw85),
	.\2 (glbl.vcc_circle));

  r_smt page1_i117  (.\1 (sw86),
	.\2 (glbl.vcc_circle));

  r_smt page1_i119  (.\1 (sw87),
	.\2 (glbl.vcc_circle));

  r_smt page1_i120  (.\1 (sw88),
	.\2 (glbl.vcc_circle));

  r_smt page1_i123  (.\1 (sw97),
	.\2 (glbl.vcc_circle));

  r_smt page1_i124  (.\1 (sw98),
	.\2 (glbl.vcc_circle));

  r_smt page1_i125  (.\1 (sw99),
	.\2 (glbl.vcc_circle));

  r_smt page1_i126  (.\1 (sw100),
	.\2 (glbl.vcc_circle));

  c_smt page1_i127  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i128  (.\1 (sw101),
	.\2 (glbl.vcc_circle));

  r_smt page1_i129  (.\1 (sw102),
	.\2 (glbl.vcc_circle));

  r_smt page1_i131  (.\1 (sw103),
	.\2 (glbl.vcc_circle));

  r_smt page1_i132  (.\1 (sw104),
	.\2 (glbl.vcc_circle));

  r_smt page1_i135  (.\1 (sw113),
	.\2 (glbl.vcc_circle));

  r_smt page1_i136  (.\1 (sw114),
	.\2 (glbl.vcc_circle));

  r_smt page1_i137  (.\1 (sw115),
	.\2 (glbl.vcc_circle));

  r_smt page1_i138  (.\1 (sw116),
	.\2 (glbl.vcc_circle));

  c_smt page1_i139  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i140  (.\1 (sw117),
	.\2 (glbl.vcc_circle));

  r_smt page1_i141  (.\1 (sw118),
	.\2 (glbl.vcc_circle));

  r_smt page1_i143  (.\1 (sw119),
	.\2 (glbl.vcc_circle));

  r_smt page1_i144  (.\1 (sw120),
	.\2 (glbl.vcc_circle));

  r_smt page1_i147  (.\1 (sw73),
	.\2 (glbl.vcc_circle));

  r_smt page1_i148  (.\1 (sw74),
	.\2 (glbl.vcc_circle));

  r_smt page1_i149  (.\1 (sw75),
	.\2 (glbl.vcc_circle));

  r_smt page1_i150  (.\1 (sw76),
	.\2 (glbl.vcc_circle));

  c_smt page1_i151  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i152  (.\1 (sw77),
	.\2 (glbl.vcc_circle));

  r_smt page1_i153  (.\1 (sw78),
	.\2 (glbl.vcc_circle));

  r_smt page1_i155  (.\1 (sw79),
	.\2 (glbl.vcc_circle));

  r_smt page1_i156  (.\1 (sw80),
	.\2 (glbl.vcc_circle));

  r_smt page1_i159  (.\1 (sw89),
	.\2 (glbl.vcc_circle));

  r_smt page1_i160  (.\1 (sw90),
	.\2 (glbl.vcc_circle));

  r_smt page1_i161  (.\1 (sw91),
	.\2 (glbl.vcc_circle));

  r_smt page1_i162  (.\1 (sw92),
	.\2 (glbl.vcc_circle));

  c_smt page1_i163  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i164  (.\1 (sw93),
	.\2 (glbl.vcc_circle));

  r_smt page1_i165  (.\1 (sw94),
	.\2 (glbl.vcc_circle));

  r_smt page1_i167  (.\1 (sw95),
	.\2 (glbl.vcc_circle));

  r_smt page1_i168  (.\1 (sw96),
	.\2 (glbl.vcc_circle));

  r_smt page1_i171  (.\1 (sw105),
	.\2 (glbl.vcc_circle));

  r_smt page1_i172  (.\1 (sw106),
	.\2 (glbl.vcc_circle));

  r_smt page1_i173  (.\1 (sw107),
	.\2 (glbl.vcc_circle));

  r_smt page1_i174  (.\1 (sw108),
	.\2 (glbl.vcc_circle));

  c_smt page1_i175  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i176  (.\1 (sw109),
	.\2 (glbl.vcc_circle));

  r_smt page1_i177  (.\1 (sw110),
	.\2 (glbl.vcc_circle));

  r_smt page1_i179  (.\1 (sw111),
	.\2 (glbl.vcc_circle));

  r_smt page1_i180  (.\1 (sw112),
	.\2 (glbl.vcc_circle));

  r_smt page1_i183  (.\1 (unnamed_1_rsmt_i183_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i184  (.\1 (unnamed_1_rsmt_i184_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i185  (.\1 (unnamed_1_rsmt_i185_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i186  (.\1 (unnamed_1_rsmt_i186_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i187  (.\1 (unnamed_1_rsmt_i187_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i188  (.\1 (unnamed_1_rsmt_i188_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i191  (.\1 (unnamed_1_rsmt_i191_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i193  (.\1 (unnamed_1_rsmt_i193_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i194  (.\1 (unnamed_1_rsmt_i194_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i195  (.\1 (unnamed_1_rsmt_i195_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i196  (.\1 (unnamed_1_rsmt_i196_1),
	.\2 (glbl.vcc_circle));

  u_74hc174 page1_i197  (.\1* (load),
	.\2 (clk),
	.\3 (sw5),
	.\4 (sw6),
	.\5 (sw7),
	.\6 (sw8),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_j5st_i2_3),
	.\10 (unnamed_1_rsmt_i183_1),
	.\11 (sw1),
	.\12 (sw2),
	.\13 (sw3),
	.\14 (sw4),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i199  (.\1* (load),
	.\2 (clk),
	.\3 (sw21),
	.\4 (sw22),
	.\5 (sw23),
	.\6 (sw24),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i184_1),
	.\10 (unnamed_1_rsmt_i191_1),
	.\11 (sw17),
	.\12 (sw18),
	.\13 (sw19),
	.\14 (sw20),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i200  (.\1* (load),
	.\2 (clk),
	.\3 (sw37),
	.\4 (sw38),
	.\5 (sw39),
	.\6 (sw40),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (/* unconnected */),
	.\10 (unnamed_1_rsmt_i196_1),
	.\11 (sw33),
	.\12 (sw34),
	.\13 (sw35),
	.\14 (sw36),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i201  (.\1* (load),
	.\2 (clk),
	.\3 (sw13),
	.\4 (sw14),
	.\5 (sw15),
	.\6 (sw16),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i183_1),
	.\10 (unnamed_1_rsmt_i184_1),
	.\11 (sw9),
	.\12 (sw10),
	.\13 (sw11),
	.\14 (sw12),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i204  (.\1* (load),
	.\2 (clk),
	.\3 (sw45),
	.\4 (sw46),
	.\5 (sw47),
	.\6 (sw48),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i196_1),
	.\10 (unnamed_1_rsmt_i195_1),
	.\11 (sw41),
	.\12 (sw42),
	.\13 (sw43),
	.\14 (sw44),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i205  (.\1* (load),
	.\2 (clk),
	.\3 (sw69),
	.\4 (sw70),
	.\5 (sw71),
	.\6 (sw72),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (/* unconnected */),
	.\10 (unnamed_1_rsmt_i185_1),
	.\11 (sw65),
	.\12 (sw66),
	.\13 (sw67),
	.\14 (sw68),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i206  (.\1* (load),
	.\2 (clk),
	.\3 (sw85),
	.\4 (sw86),
	.\5 (sw87),
	.\6 (sw88),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i186_1),
	.\10 (unnamed_1_rsmt_i188_1),
	.\11 (sw81),
	.\12 (sw82),
	.\13 (sw83),
	.\14 (sw84),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i207  (.\1* (load),
	.\2 (clk),
	.\3 (sw101),
	.\4 (sw102),
	.\5 (sw103),
	.\6 (sw104),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i187_1),
	.\10 (unnamed_1_rsmt_i193_1),
	.\11 (sw97),
	.\12 (sw98),
	.\13 (sw99),
	.\14 (sw100),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i208  (.\1* (load),
	.\2 (clk),
	.\3 (sw117),
	.\4 (sw118),
	.\5 (sw119),
	.\6 (sw120),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i194_1),
	.\10 (glbl.ground),
	.\11 (sw113),
	.\12 (sw114),
	.\13 (sw115),
	.\14 (sw116),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i209  (.\1* (load),
	.\2 (clk),
	.\3 (sw109),
	.\4 (sw110),
	.\5 (sw111),
	.\6 (sw112),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i193_1),
	.\10 (unnamed_1_rsmt_i194_1),
	.\11 (sw105),
	.\12 (sw106),
	.\13 (sw107),
	.\14 (sw108),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i210  (.\1* (load),
	.\2 (clk),
	.\3 (sw93),
	.\4 (sw94),
	.\5 (sw95),
	.\6 (sw96),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i188_1),
	.\10 (unnamed_1_rsmt_i187_1),
	.\11 (sw89),
	.\12 (sw90),
	.\13 (sw91),
	.\14 (sw92),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_74hc174 page1_i211  (.\1* (load),
	.\2 (clk),
	.\3 (sw77),
	.\4 (sw78),
	.\5 (sw79),
	.\6 (sw80),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i185_1),
	.\10 (unnamed_1_rsmt_i186_1),
	.\11 (sw73),
	.\12 (sw74),
	.\13 (sw75),
	.\14 (sw76),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  u_pic18f4321_pdip40 page1_i212  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */),
	.\9 (/* unconnected */),
	.\10 (/* unconnected */),
	.\11 (/* unconnected */),
	.\12 (/* unconnected */),
	.\13 (/* unconnected */),
	.\14 (/* unconnected */),
	.\15 (/* unconnected */),
	.\16 (/* unconnected */),
	.\17 (/* unconnected */),
	.\18 (/* unconnected */),
	.\19 (/* unconnected */),
	.\20 (/* unconnected */),
	.\21 (/* unconnected */),
	.\22 (/* unconnected */),
	.\23 (/* unconnected */),
	.\24 (/* unconnected */),
	.\25 (/* unconnected */),
	.\26 (/* unconnected */),
	.\27 (/* unconnected */),
	.\28 (/* unconnected */),
	.\29 (/* unconnected */),
	.\30 (/* unconnected */),
	.\31 (/* unconnected */),
	.\32 (/* unconnected */),
	.\33 (/* unconnected */),
	.\34 (/* unconnected */),
	.\35 (/* unconnected */),
	.\36 (/* unconnected */),
	.\37 (/* unconnected */),
	.\38 (/* unconnected */),
	.\39 (/* unconnected */),
	.\40 (/* unconnected */));

  d_smt_signal page1_i214  (.a(/* unconnected */),
	.c(/* unconnected */));

  j_8_st page1_i215  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */));

  j_8_st page1_i216  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */));

  j_8_st page1_i217  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */));

  j_8_st page1_i218  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */));

  j_8_st page1_i219  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */));

  d_smt_signal page1_i220  (.a(/* unconnected */),
	.c(/* unconnected */));

  d_smt_signal page1_i221  (.a(/* unconnected */),
	.c(/* unconnected */));

  d_smt_signal page1_i222  (.a(/* unconnected */),
	.c(/* unconnected */));

endmodule // janko(sch_1) 
