`timescale 1ns/1ns

module janko ();
// generated by  HDL Direct 15.20-s005 24-Aug-2005
// on Mon Nov 01 12:57:49 2010
// from janko_lib/JANKO/sch_1

  // global signal glbl.ground;
  // global signal glbl.vcc_circle;

  wire  clk;
  wire  load;
  wire  sw1;
  wire  sw10;
  wire  sw100;
  wire  sw101;
  wire  sw102;
  wire  sw103;
  wire  sw104;
  wire  sw105;
  wire  sw106;
  wire  sw107;
  wire  sw108;
  wire  sw109;
  wire  sw11;
  wire  sw110;
  wire  sw111;
  wire  sw112;
  wire  sw113;
  wire  sw114;
  wire  sw115;
  wire  sw116;
  wire  sw117;
  wire  sw118;
  wire  sw119;
  wire  sw12;
  wire  sw120;
  wire  sw13;
  wire  sw14;
  wire  sw15;
  wire  sw16;
  wire  sw17;
  wire  sw18;
  wire  sw19;
  wire  sw2;
  wire  sw20;
  wire  sw21;
  wire  sw22;
  wire  sw23;
  wire  sw24;
  wire  sw25;
  wire  sw26;
  wire  sw27;
  wire  sw28;
  wire  sw29;
  wire  sw3;
  wire  sw30;
  wire  sw31;
  wire  sw32;
  wire  sw33;
  wire  sw34;
  wire  sw35;
  wire  sw36;
  wire  sw37;
  wire  sw38;
  wire  sw39;
  wire  sw4;
  wire  sw40;
  wire  sw41;
  wire  sw42;
  wire  sw43;
  wire  sw44;
  wire  sw45;
  wire  sw46;
  wire  sw47;
  wire  sw48;
  wire  sw49;
  wire  sw5;
  wire  sw50;
  wire  sw51;
  wire  sw52;
  wire  sw53;
  wire  sw54;
  wire  sw55;
  wire  sw56;
  wire  sw57;
  wire  sw58;
  wire  sw59;
  wire  sw6;
  wire  sw60;
  wire  sw61;
  wire  sw62;
  wire  sw63;
  wire  sw64;
  wire  sw65;
  wire  sw66;
  wire  sw67;
  wire  sw68;
  wire  sw69;
  wire  sw7;
  wire  sw70;
  wire  sw71;
  wire  sw72;
  wire  sw73;
  wire  sw74;
  wire  sw75;
  wire  sw76;
  wire  sw77;
  wire  sw78;
  wire  sw79;
  wire  sw8;
  wire  sw80;
  wire  sw81;
  wire  sw82;
  wire  sw83;
  wire  sw84;
  wire  sw85;
  wire  sw86;
  wire  sw87;
  wire  sw88;
  wire  sw89;
  wire  sw9;
  wire  sw90;
  wire  sw91;
  wire  sw92;
  wire  sw93;
  wire  sw94;
  wire  sw95;
  wire  sw96;
  wire  sw97;
  wire  sw98;
  wire  sw99;
  wire  unnamed_1_j5st_i2_3;
  wire  unnamed_1_rsmt_i189_1;
  wire  unnamed_1_rsmt_i195_1;
  wire  unnamed_1_ucd4094_i109_10;
  wire  unnamed_1_ucd4094_i109_9;
  wire  unnamed_1_ucd4094_i121_10;
  wire  unnamed_1_ucd4094_i121_9;
  wire  unnamed_1_ucd4094_i133_10;
  wire  unnamed_1_ucd4094_i133_9;
  wire  unnamed_1_ucd4094_i145_9;
  wire  unnamed_1_ucd4094_i1_10;
  wire  unnamed_1_ucd4094_i37_10;
  wire  unnamed_1_ucd4094_i61_10;
  wire  unnamed_1_ucd4094_i73_10;
  wire  unnamed_1_ucd4094_i85_10;

  wire  ground;
  wire  page1_ground;
  wire  vcc_circle;
  wire  page1_vcc_circle;

  assign ground = glbl.ground;
  assign page1_ground = ground;
  assign vcc_circle = glbl.vcc_circle;
  assign page1_vcc_circle = vcc_circle;

  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;
  assign vcc_circle  = glbl.vcc_circle;
  assign ground  = glbl.ground;

// begin instances 

  u_cd4094 page1_i1  (.\1 (load),
	.\2 (clk),
	.\3 (sw5),
	.\4 (sw6),
	.\5 (sw7),
	.\6 (sw8),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_j5st_i2_3),
	.\10 (unnamed_1_ucd4094_i1_10),
	.\11 (sw1),
	.\12 (sw2),
	.\13 (sw3),
	.\14 (sw4),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  j_5_st page1_i2  (.\1 (glbl.ground),
	.\2 (glbl.vcc_circle),
	.\3 (unnamed_1_j5st_i2_3),
	.\4 (clk),
	.\5 (load));

  r_smt page1_i5  (.\1 (sw4),
	.\2 (glbl.vcc_circle));

  r_smt page1_i7  (.\1 (sw3),
	.\2 (glbl.vcc_circle));

  r_smt page1_i8  (.\1 (sw2),
	.\2 (glbl.vcc_circle));

  r_smt page1_i9  (.\1 (sw1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i10  (.\1 (sw5),
	.\2 (glbl.vcc_circle));

  r_smt page1_i11  (.\1 (sw6),
	.\2 (glbl.vcc_circle));

  r_smt page1_i12  (.\1 (sw7),
	.\2 (glbl.vcc_circle));

  r_smt page1_i13  (.\1 (sw8),
	.\2 (glbl.vcc_circle));

  c_smt page1_i14  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i15  (.\1 (sw57),
	.\2 (glbl.vcc_circle));

  c_smt page1_i16  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i17  (.\1 (sw58),
	.\2 (glbl.vcc_circle));

  r_smt page1_i18  (.\1 (sw59),
	.\2 (glbl.vcc_circle));

  r_smt page1_i19  (.\1 (sw60),
	.\2 (glbl.vcc_circle));

  r_smt page1_i20  (.\1 (sw61),
	.\2 (glbl.vcc_circle));

  r_smt page1_i21  (.\1 (sw62),
	.\2 (glbl.vcc_circle));

  r_smt page1_i23  (.\1 (sw63),
	.\2 (glbl.vcc_circle));

  r_smt page1_i24  (.\1 (sw64),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i25  (.\1 (load),
	.\2 (clk),
	.\3 (sw61),
	.\4 (sw62),
	.\5 (sw63),
	.\6 (sw64),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i189_1),
	.\10 (unnamed_1_ucd4094_i109_9),
	.\11 (sw57),
	.\12 (sw58),
	.\13 (sw59),
	.\14 (sw60),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i27  (.\1 (sw9),
	.\2 (glbl.vcc_circle));

  c_smt page1_i28  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i29  (.\1 (sw10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i30  (.\1 (sw11),
	.\2 (glbl.vcc_circle));

  r_smt page1_i31  (.\1 (sw12),
	.\2 (glbl.vcc_circle));

  r_smt page1_i32  (.\1 (sw13),
	.\2 (glbl.vcc_circle));

  r_smt page1_i33  (.\1 (sw14),
	.\2 (glbl.vcc_circle));

  r_smt page1_i35  (.\1 (sw15),
	.\2 (glbl.vcc_circle));

  r_smt page1_i36  (.\1 (sw16),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i37  (.\1 (load),
	.\2 (clk),
	.\3 (sw13),
	.\4 (sw14),
	.\5 (sw15),
	.\6 (sw16),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i1_10),
	.\10 (unnamed_1_ucd4094_i37_10),
	.\11 (sw9),
	.\12 (sw10),
	.\13 (sw11),
	.\14 (sw12),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i39  (.\1 (sw49),
	.\2 (glbl.vcc_circle));

  c_smt page1_i40  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i41  (.\1 (sw50),
	.\2 (glbl.vcc_circle));

  r_smt page1_i42  (.\1 (sw51),
	.\2 (glbl.vcc_circle));

  r_smt page1_i43  (.\1 (sw52),
	.\2 (glbl.vcc_circle));

  r_smt page1_i44  (.\1 (sw53),
	.\2 (glbl.vcc_circle));

  r_smt page1_i45  (.\1 (sw54),
	.\2 (glbl.vcc_circle));

  r_smt page1_i47  (.\1 (sw55),
	.\2 (glbl.vcc_circle));

  r_smt page1_i48  (.\1 (sw56),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i49  (.\1 (load),
	.\2 (clk),
	.\3 (sw53),
	.\4 (sw54),
	.\5 (sw55),
	.\6 (sw56),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_rsmt_i195_1),
	.\10 (unnamed_1_rsmt_i189_1),
	.\11 (sw49),
	.\12 (sw50),
	.\13 (sw51),
	.\14 (sw52),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i51  (.\1 (sw17),
	.\2 (glbl.vcc_circle));

  c_smt page1_i52  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i53  (.\1 (sw18),
	.\2 (glbl.vcc_circle));

  r_smt page1_i54  (.\1 (sw19),
	.\2 (glbl.vcc_circle));

  r_smt page1_i55  (.\1 (sw20),
	.\2 (glbl.vcc_circle));

  r_smt page1_i56  (.\1 (sw21),
	.\2 (glbl.vcc_circle));

  r_smt page1_i57  (.\1 (sw22),
	.\2 (glbl.vcc_circle));

  r_smt page1_i59  (.\1 (sw23),
	.\2 (glbl.vcc_circle));

  r_smt page1_i60  (.\1 (sw24),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i61  (.\1 (load),
	.\2 (clk),
	.\3 (sw21),
	.\4 (sw22),
	.\5 (sw23),
	.\6 (sw24),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i37_10),
	.\10 (unnamed_1_ucd4094_i61_10),
	.\11 (sw17),
	.\12 (sw18),
	.\13 (sw19),
	.\14 (sw20),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i63  (.\1 (sw25),
	.\2 (glbl.vcc_circle));

  c_smt page1_i64  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i65  (.\1 (sw26),
	.\2 (glbl.vcc_circle));

  r_smt page1_i66  (.\1 (sw27),
	.\2 (glbl.vcc_circle));

  r_smt page1_i67  (.\1 (sw28),
	.\2 (glbl.vcc_circle));

  r_smt page1_i68  (.\1 (sw29),
	.\2 (glbl.vcc_circle));

  r_smt page1_i69  (.\1 (sw30),
	.\2 (glbl.vcc_circle));

  r_smt page1_i71  (.\1 (sw31),
	.\2 (glbl.vcc_circle));

  r_smt page1_i72  (.\1 (sw32),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i73  (.\1 (load),
	.\2 (clk),
	.\3 (sw29),
	.\4 (sw30),
	.\5 (sw31),
	.\6 (sw32),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i61_10),
	.\10 (unnamed_1_ucd4094_i73_10),
	.\11 (sw25),
	.\12 (sw26),
	.\13 (sw27),
	.\14 (sw28),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i75  (.\1 (sw33),
	.\2 (glbl.vcc_circle));

  c_smt page1_i76  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i77  (.\1 (sw34),
	.\2 (glbl.vcc_circle));

  r_smt page1_i78  (.\1 (sw35),
	.\2 (glbl.vcc_circle));

  r_smt page1_i79  (.\1 (sw36),
	.\2 (glbl.vcc_circle));

  r_smt page1_i80  (.\1 (sw37),
	.\2 (glbl.vcc_circle));

  r_smt page1_i81  (.\1 (sw38),
	.\2 (glbl.vcc_circle));

  r_smt page1_i83  (.\1 (sw39),
	.\2 (glbl.vcc_circle));

  r_smt page1_i84  (.\1 (sw40),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i85  (.\1 (load),
	.\2 (clk),
	.\3 (sw37),
	.\4 (sw38),
	.\5 (sw39),
	.\6 (sw40),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i73_10),
	.\10 (unnamed_1_ucd4094_i85_10),
	.\11 (sw33),
	.\12 (sw34),
	.\13 (sw35),
	.\14 (sw36),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i87  (.\1 (sw41),
	.\2 (glbl.vcc_circle));

  c_smt page1_i88  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i89  (.\1 (sw42),
	.\2 (glbl.vcc_circle));

  r_smt page1_i90  (.\1 (sw43),
	.\2 (glbl.vcc_circle));

  r_smt page1_i91  (.\1 (sw44),
	.\2 (glbl.vcc_circle));

  r_smt page1_i92  (.\1 (sw45),
	.\2 (glbl.vcc_circle));

  r_smt page1_i93  (.\1 (sw46),
	.\2 (glbl.vcc_circle));

  r_smt page1_i95  (.\1 (sw47),
	.\2 (glbl.vcc_circle));

  r_smt page1_i96  (.\1 (sw48),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i97  (.\1 (load),
	.\2 (clk),
	.\3 (sw45),
	.\4 (sw46),
	.\5 (sw47),
	.\6 (sw48),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i85_10),
	.\10 (unnamed_1_rsmt_i195_1),
	.\11 (sw41),
	.\12 (sw42),
	.\13 (sw43),
	.\14 (sw44),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i99  (.\1 (sw65),
	.\2 (glbl.vcc_circle));

  r_smt page1_i100  (.\1 (sw66),
	.\2 (glbl.vcc_circle));

  r_smt page1_i101  (.\1 (sw67),
	.\2 (glbl.vcc_circle));

  r_smt page1_i102  (.\1 (sw68),
	.\2 (glbl.vcc_circle));

  c_smt page1_i103  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i104  (.\1 (sw69),
	.\2 (glbl.vcc_circle));

  r_smt page1_i105  (.\1 (sw70),
	.\2 (glbl.vcc_circle));

  r_smt page1_i107  (.\1 (sw71),
	.\2 (glbl.vcc_circle));

  r_smt page1_i108  (.\1 (sw72),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i109  (.\1 (load),
	.\2 (clk),
	.\3 (sw69),
	.\4 (sw70),
	.\5 (sw71),
	.\6 (sw72),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i109_9),
	.\10 (unnamed_1_ucd4094_i109_10),
	.\11 (sw65),
	.\12 (sw66),
	.\13 (sw67),
	.\14 (sw68),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i111  (.\1 (sw81),
	.\2 (glbl.vcc_circle));

  r_smt page1_i112  (.\1 (sw82),
	.\2 (glbl.vcc_circle));

  r_smt page1_i113  (.\1 (sw83),
	.\2 (glbl.vcc_circle));

  r_smt page1_i114  (.\1 (sw84),
	.\2 (glbl.vcc_circle));

  c_smt page1_i115  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i116  (.\1 (sw85),
	.\2 (glbl.vcc_circle));

  r_smt page1_i117  (.\1 (sw86),
	.\2 (glbl.vcc_circle));

  r_smt page1_i119  (.\1 (sw87),
	.\2 (glbl.vcc_circle));

  r_smt page1_i120  (.\1 (sw88),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i121  (.\1 (load),
	.\2 (clk),
	.\3 (sw85),
	.\4 (sw86),
	.\5 (sw87),
	.\6 (sw88),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i121_9),
	.\10 (unnamed_1_ucd4094_i121_10),
	.\11 (sw81),
	.\12 (sw82),
	.\13 (sw83),
	.\14 (sw84),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i123  (.\1 (sw97),
	.\2 (glbl.vcc_circle));

  r_smt page1_i124  (.\1 (sw98),
	.\2 (glbl.vcc_circle));

  r_smt page1_i125  (.\1 (sw99),
	.\2 (glbl.vcc_circle));

  r_smt page1_i126  (.\1 (sw100),
	.\2 (glbl.vcc_circle));

  c_smt page1_i127  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i128  (.\1 (sw101),
	.\2 (glbl.vcc_circle));

  r_smt page1_i129  (.\1 (sw102),
	.\2 (glbl.vcc_circle));

  r_smt page1_i131  (.\1 (sw103),
	.\2 (glbl.vcc_circle));

  r_smt page1_i132  (.\1 (sw104),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i133  (.\1 (load),
	.\2 (clk),
	.\3 (sw101),
	.\4 (sw102),
	.\5 (sw103),
	.\6 (sw104),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i133_9),
	.\10 (unnamed_1_ucd4094_i133_10),
	.\11 (sw97),
	.\12 (sw98),
	.\13 (sw99),
	.\14 (sw100),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i135  (.\1 (sw113),
	.\2 (glbl.vcc_circle));

  r_smt page1_i136  (.\1 (sw114),
	.\2 (glbl.vcc_circle));

  r_smt page1_i137  (.\1 (sw115),
	.\2 (glbl.vcc_circle));

  r_smt page1_i138  (.\1 (sw116),
	.\2 (glbl.vcc_circle));

  c_smt page1_i139  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i140  (.\1 (sw117),
	.\2 (glbl.vcc_circle));

  r_smt page1_i141  (.\1 (sw118),
	.\2 (glbl.vcc_circle));

  r_smt page1_i143  (.\1 (sw119),
	.\2 (glbl.vcc_circle));

  r_smt page1_i144  (.\1 (sw120),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i145  (.\1 (load),
	.\2 (clk),
	.\3 (sw117),
	.\4 (sw118),
	.\5 (sw119),
	.\6 (sw120),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i145_9),
	.\10 (glbl.ground),
	.\11 (sw113),
	.\12 (sw114),
	.\13 (sw115),
	.\14 (sw116),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i147  (.\1 (sw73),
	.\2 (glbl.vcc_circle));

  r_smt page1_i148  (.\1 (sw74),
	.\2 (glbl.vcc_circle));

  r_smt page1_i149  (.\1 (sw75),
	.\2 (glbl.vcc_circle));

  r_smt page1_i150  (.\1 (sw76),
	.\2 (glbl.vcc_circle));

  c_smt page1_i151  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i152  (.\1 (sw77),
	.\2 (glbl.vcc_circle));

  r_smt page1_i153  (.\1 (sw78),
	.\2 (glbl.vcc_circle));

  r_smt page1_i155  (.\1 (sw79),
	.\2 (glbl.vcc_circle));

  r_smt page1_i156  (.\1 (sw80),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i157  (.\1 (load),
	.\2 (clk),
	.\3 (sw77),
	.\4 (sw78),
	.\5 (sw79),
	.\6 (sw80),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i109_10),
	.\10 (unnamed_1_ucd4094_i121_9),
	.\11 (sw73),
	.\12 (sw74),
	.\13 (sw75),
	.\14 (sw76),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i159  (.\1 (sw89),
	.\2 (glbl.vcc_circle));

  r_smt page1_i160  (.\1 (sw90),
	.\2 (glbl.vcc_circle));

  r_smt page1_i161  (.\1 (sw91),
	.\2 (glbl.vcc_circle));

  r_smt page1_i162  (.\1 (sw92),
	.\2 (glbl.vcc_circle));

  c_smt page1_i163  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i164  (.\1 (sw93),
	.\2 (glbl.vcc_circle));

  r_smt page1_i165  (.\1 (sw94),
	.\2 (glbl.vcc_circle));

  r_smt page1_i167  (.\1 (sw95),
	.\2 (glbl.vcc_circle));

  r_smt page1_i168  (.\1 (sw96),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i169  (.\1 (load),
	.\2 (clk),
	.\3 (sw93),
	.\4 (sw94),
	.\5 (sw95),
	.\6 (sw96),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i121_10),
	.\10 (unnamed_1_ucd4094_i133_9),
	.\11 (sw89),
	.\12 (sw90),
	.\13 (sw91),
	.\14 (sw92),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i171  (.\1 (sw105),
	.\2 (glbl.vcc_circle));

  r_smt page1_i172  (.\1 (sw106),
	.\2 (glbl.vcc_circle));

  r_smt page1_i173  (.\1 (sw107),
	.\2 (glbl.vcc_circle));

  r_smt page1_i174  (.\1 (sw108),
	.\2 (glbl.vcc_circle));

  c_smt page1_i175  (.\1 (glbl.vcc_circle),
	.\2 (glbl.ground));

  r_smt page1_i176  (.\1 (sw109),
	.\2 (glbl.vcc_circle));

  r_smt page1_i177  (.\1 (sw110),
	.\2 (glbl.vcc_circle));

  r_smt page1_i179  (.\1 (sw111),
	.\2 (glbl.vcc_circle));

  r_smt page1_i180  (.\1 (sw112),
	.\2 (glbl.vcc_circle));

  u_cd4094 page1_i181  (.\1 (load),
	.\2 (clk),
	.\3 (sw109),
	.\4 (sw110),
	.\5 (sw111),
	.\6 (sw112),
	.\7 (/* unconnected */),
	.\8 (glbl.ground),
	.\9 (unnamed_1_ucd4094_i133_10),
	.\10 (unnamed_1_ucd4094_i145_9),
	.\11 (sw105),
	.\12 (sw106),
	.\13 (sw107),
	.\14 (sw108),
	.\15 (glbl.ground),
	.\16 (glbl.vcc_circle));

  r_smt page1_i183  (.\1 (unnamed_1_ucd4094_i1_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i184  (.\1 (unnamed_1_ucd4094_i37_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i185  (.\1 (unnamed_1_ucd4094_i109_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i186  (.\1 (unnamed_1_ucd4094_i121_9),
	.\2 (glbl.vcc_circle));

  r_smt page1_i187  (.\1 (unnamed_1_ucd4094_i133_9),
	.\2 (glbl.vcc_circle));

  r_smt page1_i188  (.\1 (unnamed_1_ucd4094_i121_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i189  (.\1 (unnamed_1_rsmt_i189_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i190  (.\1 (unnamed_1_ucd4094_i109_9),
	.\2 (glbl.vcc_circle));

  r_smt page1_i191  (.\1 (unnamed_1_ucd4094_i61_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i192  (.\1 (unnamed_1_ucd4094_i73_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i193  (.\1 (unnamed_1_ucd4094_i133_10),
	.\2 (glbl.vcc_circle));

  r_smt page1_i194  (.\1 (unnamed_1_ucd4094_i145_9),
	.\2 (glbl.vcc_circle));

  r_smt page1_i195  (.\1 (unnamed_1_rsmt_i195_1),
	.\2 (glbl.vcc_circle));

  r_smt page1_i196  (.\1 (unnamed_1_ucd4094_i85_10),
	.\2 (glbl.vcc_circle));

endmodule // janko(sch_1) 
