`timescale 1ns/1ns

module buttons ();
// generated by  HDL Direct 16.3-S021 (v16-3-85AK) 12/6/2010
// on Sun Sep 30 21:28:19 2012
// from buttons_lib/BUTTONS/sch_1

// begin instances 

  j_3_st page1_i1  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */));

endmodule // buttons(sch_1) 
